version: "3.4"
services:
  postgres_users:
    container_name: postgres_users
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db

  api_nest:
    restart: always
    container_name: api_nest
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    depends_on:
      - postgres_users 
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
      DATABASE_URL: postgres://user:password@postgres_users:5432/db
      NODE_ENV: development
      PORT: 3001
    entrypoint:
      - npm
      - run
      - start:dev
    ports:
      - "4000:3001"
    volumes:
      - ./:/app

networks:
  postgres:
    driver: bridge